version: '3.9'
services:
  db:
    image: mysql:8.0.21
    container_name: db
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
  backend: 
    build: ./backend
    container_name: app_backend
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/dg_solutions_users
  frontend:
    build: ./frontend
    container_name: app_frontend
    ports:
      - 3000:3000
    depends_on:
      - backend